import assert from "node:assert/strict";
import test from "node:test";

async function render(path = "/") {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(new Request(`http://localhost${path}`, { headers: { accept: "text/html" } }), {
    ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) },
  }, { waitUntil() {}, passThroughOnException() {} });
}

test("server-renders the neural multimodal data service homepage", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /<html lang="zh-CN">/);
  assert.match(html, /<title>全域智能｜神经多模态数据服务<\/title>/);
  assert.match(html, /<h1>定义以人为中心的神经信号数采新范式<\/h1>/);
  assert.match(html, /预约体验/);
  assert.match(html, /以规模化大脑数采和大脑基座模型为核心，帮助下一代AI理解人类的价值判断、内在状态与个体偏好/);
  assert.match(html, /通过采集和解析脑电等神经信号，将人的注意、意图、情绪、疲劳和错误感知转化为AI可使用的信息。/);
  assert.match(html, /让AI在训练阶段学习人的判断与偏好，在使用过程中持续理解人的状态并作出响应。/);
  assert.match(html, /在数据层上提供包括采集、去噪（EEGdenoiseNet）、脑电溯源（Nature BME）、大脑的数字孪生（Nature Methods）在内的全链路技术。/);
  assert.match(html, /当所有人都在造更快的 AI，我们在造更懂人的 AI。/);
  assert.doesNotMatch(html, /从研究设计到标准化数据交付/);
  assert.doesNotMatch(html, /真实采集设备、实验范式、多模态数据结构与技术验证/);
  assert.doesNotMatch(html, /围绕神经信号建立可执行、可同步、可解析、可规模化的完整数据服务/);
  assert.doesNotMatch(html, /不只记录单一信号，而是将神经、生理、行为、任务与环境信息组织为可对齐的数据体系/);
  assert.doesNotMatch(html, /以公开论文和数据集记录实验方法、数据规模与可复现结果/);
  assert.doesNotMatch(html, /<span>能力 /);
  assert.doesNotMatch(html, /<span>场景 /);
  assert.match(html, /src="\/omni-intelligence-logo\.svg"/);
  assert.doesNotMatch(html, /LOGO_WORDMARK/);
  assert.doesNotMatch(html, /HERO_VIDEO_PLACEHOLDER/);
  assert.doesNotMatch(html, /metric__value|StatisticsDashboard/);
  assert.match(html, /汉脑交响/);
  assert.match(html, /data-count-target="27"/);
  assert.doesNotMatch(html, /class="capability-cards"/);
  assert.match(html, /class="application-cards"/);
  assert.match(html, /多模态数据体系/);
  assert.match(html, /神经与生理信号/);
  assert.match(html, /眼动与行为数据/);
  assert.match(html, /任务与场景上下文/);
  assert.match(html, /任务指令 \/ 任务状态 \/ 视觉与听觉刺激 \/ 环境状态/);
  assert.match(html, /应用方向/);
  assert.match(html, /大脑基座模型/);
  assert.match(html, /跨被试泛化、多任务复用/);
  assert.match(html, /预训练 · 后训练 · 下游验证/);
  assert.match(html, /状态感知 · 意图理解 · 交互响应/);
  assert.doesNotMatch(html, /面向真实应用/);
  assert.doesNotMatch(html, /神经、生理与眼动信号/);
  assert.doesNotMatch(html, /内容与环境数据/);
  assert.doesNotMatch(html, /为科学研究、脑机接口基座模型与智能体交互提供可验证的数据基础/);
  assert.doesNotMatch(html, /研究能力概览/);
  assert.doesNotMatch(html, /核心能力/);
  assert.doesNotMatch(html, /围绕目标任务采集脑电等神经信号/);
  assert.doesNotMatch(html, /同步采集脑电、肌电、眼动、行为、任务与环境信息/);
  assert.doesNotMatch(html, /全链路数据技术/);
  assert.doesNotMatch(html, /神经信号解析与标注/);
  assert.doesNotMatch(html, /神经信号处理与标注/);
  assert.doesNotMatch(html, /规模化数据服务/);
  assert.ok(html.indexOf("<h2>研究成果</h2>") < html.indexOf("<h2>应用方向</h2>"));
  assert.match(html, /脑电数据采集流程示例/);
  assert.match(html, /肌电数据采集流程示例/);
  assert.doesNotMatch(html, /以真实采集设备、实验平台和规范流程/);
  assert.doesNotMatch(html, /通过设备、平台与任务流程协同/);
  assert.doesNotMatch(html, /脑电采集 \/ 图片|肌电采集 \/ 视频/);
  assert.doesNotMatch(html, /RESEARCH STANDARD/);
  assert.doesNotMatch(html, /NEURAL DATA INFRASTRUCTURE/);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape|react-loading-skeleton/);
});

test("renders the required semantic anchors and production contact details", async () => {
  const html = await (await render()).text();
  for (const id of ["services", "research", "order"]) assert.match(html, new RegExp(`id="${id}"`));
  assert.doesNotMatch(html, /href="\/papers/);
  assert.match(html, /href="\/products\/neural-data"/);
  assert.match(html, />数采中心</);
  assert.ok(html.indexOf('href="#research"') < html.indexOf('href="/products/neural-data"'));
  assert.match(html, />查看更多</);
  assert.doesNotMatch(html, />数据产品</);
  assert.match(html, /eeg-collection\.webp/);
  assert.doesNotMatch(html, /EEG_COLLECTION_IMAGE_PLACEHOLDER/);
  assert.match(html, /emg-collection-poster\.webp/);
  assert.match(html, /emg-collection\.webm/);
  assert.match(html, /sales@omni-intel\.cn/);
  assert.match(html, /src="\/wechat\.webp"/);
  assert.match(html, /深圳全域智能/);
  assert.match(html, /粤ICP备2026043468号-1/);
  assert.match(html, /href="https:\/\/beian\.miit\.gov\.cn\//);
  assert.doesNotMatch(html, /扫码关注公众号或来信时/);
  assert.match(html, /name="botcheck"/);
  assert.doesNotMatch(html, /ICP_RECORD_NUMBER/);
  assert.doesNotMatch(html, /TODO_CONTENT_REVIEW/);
});

test("renders research as a homepage carousel with dataset counters", async () => {
  const html = await (await render()).text();
  assert.match(html, /class="paper-carousel"/);
  assert.equal((html.match(/class="paper-slide(?: is-active)?"/g) ?? []).length, 5);
  assert.doesNotMatch(html, /s41597-025-06466-8/);
  assert.match(html, /Multi-dataset Joint Pre-training of Emotional EEG Enables Generalizable Affective Computing/);
  assert.match(html, /A Multi-Context Emotional EEG Dataset for Cross-Context Emotion Decoding/);
  assert.match(html, /ChineseEEG: A Chinese Linguistic Corpora EEG Dataset for Semantic Alignment and Neural Decoding/);
  assert.match(html, /EEGdenoiseNet: a benchmark dataset for deep learning solutions of EEG denoising/);
  assert.match(html, /Scientific Data/);
  assert.match(html, /Journal of Neural Engineering/);
  assert.doesNotMatch(html, /论文图片待补充/);
  assert.match(html, /multi-dataset-joint-pre-training\.webp/);
  assert.match(html, /style="width:95%"/);
  assert.match(html, /chineseEEG2\.webp/);
  assert.match(html, /emotional-eeg\.webp/);
  assert.match(html, /chineseEEG\.webp/);
  assert.match(html, /EEGdenoiseNet\.webp/);
  assert.equal((html.match(/paper-slide__asset--fit-width/g) ?? []).length, 2);
  assert.equal((html.match(/paper-slide__asset--fit-height/g) ?? []).length, 3);
  assert.match(html, /2508\.04240[\s\S]*s41597-025-05349-2[\s\S]*s41597-024-03398-7[\s\S]*2510\.22197[\s\S]*1741-2552\/ac2bf8/);
  assert.match(html, /ChineseEEG-2/);
  assert.match(html, /ChineseEEG/);
  assert.match(html, /EmoEEG-MC/);
  assert.match(html, /sciencedb\.CHNNeuro\.00001/);
  assert.match(html, /sciencedb\.CHNNeuro\.00007/);
  assert.match(html, /dataSetId=9b182864c9604255a0433d1edae88f0b/);
  for (const value of [27, 8, 3, 15]) assert.match(html, new RegExp(`data-count-target="${value}"`));
  assert.match(html, /research-datasets__list[\s\S]*EmoEEG-MC[\s\S]*ChineseEEG[\s\S]*ChineseEEG-2/);
  assert.doesNotMatch(html, /上一张|下一张/);
  assert.doesNotMatch(html, /class="papers-row"/);
});

test("does not expose a standalone research-results page", async () => {
  const response = await render("/papers");
  assert.equal(response.status, 404);
});

test("renders the dedicated neural data product page", async () => {
  const html = await (await render("/products/neural-data")).text();
  assert.match(html, /神经多模态数据服务/);
  assert.doesNotMatch(html, /设备 · 平台 · 流程/);
  assert.match(html, /面向大脑基座模型、科学研究与智能体交互/);
  assert.match(html, /围绕研究问题、模型任务或交互场景/);
  assert.match(html, /脑电数据采集流程示例/);
  assert.match(html, /肌电数据采集流程示例/);
  assert.match(html, /eeg-collection\.webp/);
  assert.doesNotMatch(html, /EEG_COLLECTION_IMAGE_PLACEHOLDER/);
  assert.match(html, /emg-collection-poster\.webp/);
  assert.match(html, /emg-collection\.mp4/);
  assert.match(html, /id="eeg"/);
  assert.match(html, /id="emg"/);
  assert.match(html, /服务流程/);
  assert.doesNotMatch(html, /从需求澄清到结构化数据交付，每一步都保留明确的输入、执行与验证记录/);
  assert.match(html, /当所有人都在造更快的 AI，我们在造更懂人的 AI。/);
  assert.doesNotMatch(html, /从一项真实任务开始设计采集方案/);
  assert.doesNotMatch(html, /告诉我们目标、场景与需要采集的数据模态/);
  assert.match(html, /©[\s\S]*?\d{4}[\s\S]*?全域智能 \/ Omni-Intelligence/);
  assert.match(html, /粤ICP备2026043468号-1/);
  assert.match(html, /class="container site-footer__inner"/);
  assert.match(html, /需求澄清与数据设计/);
  assert.match(html, /范式与预实验验证/);
  assert.match(html, /多模态采集与在线质控/);
  assert.match(html, /数据处理、对齐与标注/);
  assert.match(html, /结构化交付与下游验证/);
  assert.match(html, /事件与状态标注/);
  assert.match(html, /模型训练与下游任务验证/);
  assert.doesNotMatch(html, /语义标注/);
  assert.doesNotMatch(html, /支持具身智能和人机协作研究/);
  assert.ok(html.indexOf('href="/#research"') < html.indexOf('href="/products/neural-data"'));
  assert.match(html, /id="order-panel-title">联系我们/);
  assert.match(html, /class="required-mark"[^>]*>\*</);
  assert.equal((html.match(/class="optional-mark"/g) ?? []).length, 3);
  assert.doesNotMatch(html, /预计规模|期望时间|现有范式链接\/说明/);
  assert.doesNotMatch(html, /class="task-types"|>任务类型</);
  assert.equal((html.match(/id="order-panel-title"/g) ?? []).length, 1);
});
